// Shared domain types for the IRIS client (mirrors the server's data shapes).

export interface Point {
  x: number;
  y: number;
}

/** Drag start snapshot: [startX/scaleX, startY/scaleY, stackX, stackY, stackIndex]. */
export type DragStart = [number, number, number, number, number];

/** URLs generated by the server for an uploaded image and its renditions. */
export interface ImageFileRefs {
  url: string;
  path: string;
  webUrl: string;
  smallUrl: string;
  mediumUrl: string;
}

/** One layer inside an image stack (fixed image or moving image slice). */
export interface ImageEntry {
  stackId?: number;
  id: string;
  checked?: boolean;
  width?: number;
  height?: number;
  base64?: string;
  imageUrl?: string;
  thumbnailUrl?: string;
  galleryUrl?: string;
  files?: ImageFileRefs;
  file?: {
    name: string;
    lastModified: number;
    relativePath: string;
  };
  [key: string]: unknown;
}

/** A stack of images positioned relative to the fixed image. */
export interface WorkingImage {
  id: number;
  x: number;
  y: number;
  width?: number;
  height?: number;
  scaling?: number;
  rotation?: number;
  opacity?: number;
  imageEntries: ImageEntry[];
}

/** The editor's present state ("settings.json" content + UI-only fields). */
export interface EditorSettings {
  loading: boolean;
  id: string;
  title?: string;
  worldScale: number;
  workingImages: WorkingImage[];
  dragStart: DragStart | null;
  mousepos: Point;
  orientation: number;
}

/** settings.json as persisted by the server (may lack UI-only fields). */
export interface ProjectSettingsDoc {
  id?: string;
  title?: string;
  worldScale?: number;
  workingImages: WorkingImage[];
  thumbnail?: string;
  uploaded?: number;
  imageFixed?: WorkingImage;
  [key: string]: unknown;
}

export type StackField = "x" | "y" | "rotation" | "scaling" | "opacity";

export type SettingsAction =
  | { type: "SET_SETTINGS"; payload: EditorSettings }
  | { type: "SET_LOADING"; payload: boolean }
  | { type: "SET_STACKS"; payload: WorkingImage[] }
  | { type: "SET_TITLE"; payload: string }
  | {
      type: "UPDATE_STACK";
      payload: { stackId: number; updates: Partial<WorkingImage> };
    }
  | {
      type: "UPDATE_STACK_BY_INDEX";
      payload: { index: number; updates: Partial<WorkingImage> };
    }
  | { type: "CANVAS_DRAG_START" }
  | { type: "CANVAS_DRAG_END" }
  | {
      type: "CANVAS_DRAG_MOVE";
      payload: {
        clientX: number;
        clientY: number;
        svgScaleX: number;
        svgScaleY: number;
        dragStart?: DragStart | null;
      };
    }
  | { type: "CANVAS_UPDATE_MOUSEPOS"; payload: Point }
  | { type: "CANVAS_CYCLE_ORIENTATION" }
  | { type: "ADD_STACK"; payload: WorkingImage }
  | {
      type: "ADD_IMAGES_TO_STACK";
      payload: { stackIndex: number; imageEntries: ImageEntry[] };
    }
  | {
      type: "REPLACE_STACK_IMAGES";
      payload: {
        stackIndex: number;
        width: number;
        height: number;
        imageEntries: ImageEntry[];
      };
    }
  | {
      type: "DELETE_IMAGE_ENTRY";
      payload: { stackIndex: number; entryIndex: number };
    }
  | {
      type: "TOGGLE_IMAGE_VISIBILITY";
      payload: { stackIndex: number; entryIndex: number; checked: boolean };
    };

export type UndoRedoAction = { type: "UNDO" } | { type: "REDO" };

export type EditorAction = SettingsAction | UndoRedoAction;

export interface HistoryMeta {
  type?: string;
  time?: number;
  label?: string;
}

export interface HistoryState<S> {
  past: S[];
  present: S;
  future: S[];
  pastMeta: HistoryMeta[];
  presentMeta: HistoryMeta;
  futureMeta: HistoryMeta[];
}

/** Registration job as reported by the server (/api/status, /api/start). */
export interface Task {
  id: string;
  projectId: string;
  title?: string;
  fixedImage?: unknown;
  images?: number;
  datacubes?: number;
  thumbnail?: string;
  /** [completed, total] as reported by the Python script progress markers. */
  progress: [number | string, number | string];
  startTime?: number;
  endTime?: number;
  updated: number;
  message?: string;
  /** "queued" | "started" | "success" | "error" | "stopped" */
  status: string;
  done?: number;
}

/** Response of POST /api/upload/:id. */
export interface UploadImageResponse {
  metadata: ImageEntry;
  url: string;
  path: string;
  webUrl: string;
  smallUrl: string;
  mediumUrl: string;
}

/** Result of GET /api/status, summarised by fetchJobs(). */
export interface JobQueueSummary {
  done: number;
  queued: number;
  inProgress: number;
  failed: number;
  total: number;
  jobs: Record<string, Task>;
  jobsByProject: Partial<Record<string, Task[]>>;
}

/** Result of POST /api/server-info. */
export interface ServerInfo {
  serverUrl?: string;
  port?: number;
}

/** Transformation JSON produced by the registration pipeline. */
export interface TransformationJson {
  transformation_obtained_s3?: {
    tx?: number;
    ty?: number;
    [key: string]: unknown;
  };
  transformation_obtained_s4?: {
    mi_average?: number;
    [key: string]: unknown;
  };
  [key: string]: unknown;
}
